### PR TITLE
Add bootstrap

### PR DESCRIPTION
**Pull request by davidboll**
#### Description
Changes proposed in this pull request:

* Adds the css-framework bootstrap as a gem.
#### What I have learned working on this feature: 
That there are often many ways to do the same thing, there are often multiple ways of solving the same problem. In this case we could have added bootstrap to our project with a CDN, or just downloaded the entire thing, but we chose to add it as a gem instead.

### CODE REVIEW

**Review by diraulo — CHANGES_REQUESTED** [review]
Looks like you forgot to push the changes to `Gemfile` and `Gemfile.lock`

**Comment by davidboll** [comment]
Nice catch @diraulo ! Fixed in new commit 👍

**Review by diraulo — DISMISSED** [review]
Looks alright to me...

**Review by tochman — APPROVED** [review]
I assume that all is good. Would like to see some screenshots.

**Pull request merged**
